import pathlib
p = pathlib.Path(r"Z:/research/hydroclaude/solvers/unsteady_preissmann_solver.py")
src_lines = [
    '"""Unsteady flow Preissmann Box Scheme solver."""',
    '',
    'import numpy as np',
    'from dataclasses import dataclass',
    'from typing import Any, Optional, List',
    'import scipy.sparse as sp',
    'from scipy.sparse.linalg import spsolve',
    '',
    '',
    '@dataclass',
    'class UnsteadyReachData:',
    '    n_xs: int',
    '    dx: np.ndarray',
    '    bed_elevation: np.ndarray',
    '    manning_n: np.ndarray',
    '    sections: list',
    '',
    '',
    '@dataclass',
    'class UnsteadyState:',
    '    Z: np.ndarray',
    '    Q: np.ndarray',
    '    t: float',
    '',
    '',
    'def _safe_depth(Z: float, bed: float, min_depth: float) -> float:',
    '    return max(Z - bed, min_depth)',
    '',
    '',
    'class PreissmannSolver:',
    '    def __init__(self, reach: UnsteadyReachData, theta: float = 0.6, g: float = 9.81,',
    '                 nr_max_iter: int = 30, nr_tol: float = 1e-4,',
    '                 min_depth: float = 0.05, max_dZ_per_iter: float = 0.5):',
    '        self.reach = reach',
    '        self.theta = theta',
    '        self.g = g',
    '        self.nr_max_iter = nr_max_iter',
    '        self.nr_tol = nr_tol',
    '        self.min_depth = min_depth',
    '        self.max_dZ_per_iter = max_dZ_per_iter',
    '        self.n = reach.n_xs',
    '    def solve(self, state0: UnsteadyState, t_end: float, dt: float,',
    '              upstream_bc: Any, downstream_bc: Any,',
    '              output_interval = None, verbose: bool = False) -> dict:',
    '        reach = self.reach',
    '        n = self.n',
    '        Z = np.array(state0.Z, dtype=float)',
    '        Q = np.array(state0.Q, dtype=float)',
    '        t = float(state0.t)',
    '        for i in range(n):',
    '            if np.isnan(Z[i]): Z[i] = reach.bed_elevation[i] + self.min_depth',
    '            if np.isnan(Q[i]): Q[i] = 0.0',
    '        out_interval = dt if output_interval is None else float(output_interval)',
    '        times_out = [t]',
    '        Z_out = [Z.copy()]',
    '        Q_out = [Q.copy()]',
    '        next_out_t = t + out_interval',
    '        while t < t_end - 1e-10:',
    '            dt_actual = min(dt, t_end - t)',
    '            t_new = t + dt_actual',
    '            Z_new, Q_new, converged, nr_iter = self._advance_one_step(',
    '                Z, Q, t, t_new, dt_actual, upstream_bc, downstream_bc)',
    '            if verbose:',
    '                q_up = upstream_bc(t_new)',
    '                print(f"  t={t_new:8.1f}s  NR={nr_iter}  conv={converged}  Q={q_up:.2f}  Zmax={Z_new.max():.3f}")',
    '            Z, Q, t = Z_new, Q_new, t_new',
    '            if t >= next_out_t - 1e-10:',
    '                times_out.append(t)',
    '                Z_out.append(Z.copy())',
    '                Q_out.append(Q.copy())',
    '                next_out_t += out_interval',
    '        return {"times": np.array(times_out), "Z_history": np.array(Z_out), "Q_history": np.array(Q_out)}',
    '',
    '    def compute_mass_balance(self, result: dict) -> dict:',
    '        times = result["times"]',
    '        Z_hist = result["Z_history"]',
    '        Q_hist = result["Q_history"]',
    '        if len(times) < 2: return {"error_percent": 0.0}',
    '        reach = self.reach',
    '        vol_in  = float(np.trapz(Q_hist[:, 0],  times))',
    '        vol_out = float(np.trapz(Q_hist[:, -1], times))',
    '        def _storage(Z_arr):',
    '            s = 0.0',
    '            for i in range(reach.n_xs):',
    '                depth = max(Z_arr[i] - reach.bed_elevation[i], 0.0)',
    '                geom = reach.sections[i].compute_geometry(depth)',
    '                dx_i = (reach.dx[0]/2 if i == 0 else reach.dx[-1]/2 if i == reach.n_xs-1',
    '                        else (reach.dx[i-1]+reach.dx[i])/2)',
    '                s += geom.area * dx_i',
    '            return s',
    '        delta_s = _storage(Z_hist[-1]) - _storage(Z_hist[0])',
    '        net_in = vol_in - vol_out',
    '        if abs(net_in) < 1e-10 and abs(delta_s) < 1e-10: ep = 0.0',
    '        elif abs(net_in) < 1e-10: ep = 100.0',
    '        else: ep = abs(net_in - delta_s) / max(abs(net_in), 1e-10) * 100.0',
    '        return {"error_percent": ep}',
    '',
    '    def _advance_one_step(self, Z_n, Q_n, t_n, t_np1, dt, upstream_bc, downstream_bc):',
    '        n = self.n',
    '        reach = self.reach',
    '        Z = Z_n.copy()',
    '        Q = Q_n.copy()',
    '        Q_up = float(upstream_bc(t_np1))',
    '        A_n, B_n, K_n = self._compute_hydraulics_all(Z_n, Q_n)',
    '        converged = False',
    '        nr_iter = 0',
    '        for nr_iter in range(1, self.nr_max_iter + 1):',
    '            A, B, K = self._compute_hydraulics_all(Z, Q)',
    '            F, J = self._build_system(Z, Q, Z_n, Q_n, A, B, K, A_n, B_n, K_n,',
    '                                      dt, Q_up, t_np1, downstream_bc)',
    '            try:',
    '                delta = spsolve(J.tocsr(), -F)',
    '            except Exception:',
    '                break',
    '            if not np.all(np.isfinite(delta)): break',
    '            dZ = np.clip(delta[0::2], -self.max_dZ_per_iter, self.max_dZ_per_iter)',
    '            dQ = delta[1::2]',
    '            Z = Z + dZ',
    '            Q = Q + dQ',
    '            for i in range(n):',
    '                z_min = reach.bed_elevation[i] + self.min_depth',
    '                if Z[i] < z_min: Z[i] = z_min',
    '            if np.max(np.abs(dZ)) < self.nr_tol and np.max(np.abs(dQ)) < self.nr_tol:',
    '                converged = True',
    '                break',
    '        return Z, Q, converged, nr_iter',
    '',
    '    def _compute_hydraulics_all(self, Z, Q):',
    '        n = self.n',
    '        reach = self.reach',
    '        A = np.zeros(n)',
    '        B = np.zeros(n)',
    '        K = np.zeros(n)',
    '        for i in range(n):',
    '            depth = _safe_depth(Z[i], reach.bed_elevation[i], self.min_depth)',
    '            geom = reach.sections[i].compute_geometry(depth)',
    '            A[i] = max(geom.area, 1e-6)',
    '            B[i] = max(geom.width, 0.1)',
    '            P = max(geom.perimeter, 1e-6)',
    '            R = A[i] / P',
    '            K[i] = max((1.0 / reach.manning_n[i]) * A[i] * R ** (2.0 / 3.0), 1e-6)',
    '        return A, B, K',
    '',
    '    def _build_system(self, Z, Q, Z_n, Q_n, A, B, K, A_n, B_n, K_n, dt, Q_up, t_np1, downstream_bc):',
    '        n = len(Z)',
    '        neq = 2 * n',
    '        reach = self.reach',
    '        theta = self.theta',
    '        g = self.g',
    '        F = np.zeros(neq)',
    '        J = sp.lil_matrix((neq, neq))',
    '        F[0] = Q[0] - Q_up',
    '        J[0, 1] = 1.0',
    '        for i in range(n - 1):',
    '            dx   = reach.dx[i]',
    '            eq_c = 2 * i + 1',
    '            eq_m = 2 * i + 2',
    '            F[eq_c] = (',
    '                (A[i+1]+A[i]-A_n[i+1]-A_n[i]) / (2.0*dt)',
    '                + theta*(Q[i+1]-Q[i])/dx + (1.0-theta)*(Q_n[i+1]-Q_n[i])/dx',
    '            )',
    '            beta_l  = Q[i]**2 / A[i]',
    '            beta_r  = Q[i+1]**2 / A[i+1]',
    '            beta_ln = Q_n[i]**2 / A_n[i]',
    '            beta_rn = Q_n[i+1]**2 / A_n[i+1]',
    '            A_avg   = 0.5*(A[i]+A[i+1])',
    '            K_avg   = 0.5*(K[i]+K[i+1])',
    '            Q_avg   = 0.5*(Q[i]+Q[i+1])',
    '            K_avg_n = 0.5*(K_n[i]+K_n[i+1])',
    '            Q_avg_n = 0.5*(Q_n[i]+Q_n[i+1])',
    '            A_avg_n = 0.5*(A_n[i]+A_n[i+1])',
    '            Sf      = Q_avg   * abs(Q_avg)   / (K_avg**2   + 1e-30)',
    '            Sf_n    = Q_avg_n * abs(Q_avg_n) / (K_avg_n**2 + 1e-30)',
    '            gA      = g * A_avg',
    '            gA_n    = g * A_avg_n',
    '            F[eq_m] = (',
    '                (Q[i+1]+Q[i]-Q_n[i+1]-Q_n[i]) / (2.0*dt)',
    '                + theta*(beta_r-beta_l)/dx + (1.0-theta)*(beta_rn-beta_ln)/dx',
    '                + theta*gA*(Z[i+1]-Z[i])/dx + (1.0-theta)*gA_n*(Z_n[i+1]-Z_n[i])/dx',
    '                + theta*gA*Sf + (1.0-theta)*gA_n*Sf_n',
    '            )',
    '            J[eq_c, 2*i]       = B[i]/(2.0*dt)',
    '            J[eq_c, 2*i+1]     = -theta/dx',
    '            J[eq_c, 2*(i+1)]   = B[i+1]/(2.0*dt)',
    '            J[eq_c, 2*(i+1)+1] = theta/dx',
    '            dbeta_l_dZi   = -(Q[i]**2)/(A[i]**2)*B[i]',
    '            dbeta_l_dQi   = 2.0*Q[i]/A[i]',
    '            dbeta_r_dZip1 = -(Q[i+1]**2)/(A[i+1]**2)*B[i+1]',
    '            dbeta_r_dQip1 = 2.0*Q[i+1]/A[i+1]',
    '            K2            = K_avg**2 + 1e-30',
    '            dSf_dQavg     = 2.0*abs(Q_avg)/K2',
    '            dgASf_dZi     = g*0.5*B[i]*Sf',
    '            dgASf_dZip1   = g*0.5*B[i+1]*Sf',
    '            dgASf_dQi     = gA*dSf_dQavg*0.5',
    '            dgASf_dQip1   = gA*dSf_dQavg*0.5',
    '            dZdiff        = Z[i+1] - Z[i]',
    '            dgAdZ_dZi     = g*0.5*B[i]*dZdiff/dx - gA/dx',
    '            dgAdZ_dZip1   = g*0.5*B[i+1]*dZdiff/dx + gA/dx',
    '            J[eq_m, 2*i]       = theta*(-dbeta_l_dZi/dx + dgAdZ_dZi + dgASf_dZi)',
    '            J[eq_m, 2*i+1]     = 1.0/(2.0*dt) + theta*(-dbeta_l_dQi/dx + dgASf_dQi)',
    '            J[eq_m, 2*(i+1)]   = theta*(dbeta_r_dZip1/dx + dgAdZ_dZip1 + dgASf_dZip1)',
    '            J[eq_m, 2*(i+1)+1] = 1.0/(2.0*dt) + theta*(dbeta_r_dQip1/dx + dgASf_dQip1)',
    '        eq_ds_z = 2*(n-1)',
    '        eq_ds_q = 2*(n-1)+1',
    '        if hasattr(downstream_bc, "compute_normal_wse"):',
    '            Z_ds = downstream_bc.compute_normal_wse(Q[-1])',
    '            F[eq_ds_z] = Z[-1] - Z_ds',
    '            J[eq_ds_z, 2*(n-1)] = 1.0',
    '            dq = max(abs(Q[-1])*1e-4, 1e-4)',
    '            Z_dsp = downstream_bc.compute_normal_wse(Q[-1]+dq)',
    '            J[eq_ds_z, 2*(n-1)+1] = -(Z_dsp - Z_ds)/dq',
    '        else:',
    '            F[eq_ds_z] = Z[-1] - float(downstream_bc(t_np1))',
    '            J[eq_ds_z, 2*(n-1)] = 1.0',
    '        F[eq_ds_q] = Q[-1] - Q[-2]',
    '        J[eq_ds_q, 2*(n-1)+1] =  1.0',
    '        J[eq_ds_q, 2*(n-2)+1] = -1.0',
    '        return F, J',
    '',
]
p.write_text(chr(10).join(src_lines) + chr(10), encoding="utf-8")
print("written", p, len(src_lines), "lines")
