#!/bin/bash
# HydroClaude 测试执行示例
# 展示如何运行各种测试的具体示例

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=========================================="
echo "HydroClaude 测试执行示例"
echo "=========================================="
echo ""

# 示例 1: 后端求解器测试
echo -e "${BLUE}=== 示例 1: 后端求解器商业对标测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 验证 HydrostaticCanalSolver 与 HEC-RAS 的精度对比${NC}"
echo "命令:"
echo "  pytest tests/backend/solvers/test_hydrostatic_commercial.py::test_uniform_flow -v -s"
echo ""
echo "预期输出:"
echo "  ✅ 流量误差: 0.0001%"
echo "  ✅ 水深误差: 0.05%"
echo "  ✅ PASSED"
echo ""
echo "---"
echo ""

# 示例 2: API 测试
echo -e "${BLUE}=== 示例 2: API 端点测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 测试知识库 API 的健康检查和基本功能${NC}"
echo "命令:"
echo "  pytest tests/backend/api/test_knowledge_api.py::test_health_check -v"
echo ""
echo "预期输出:"
echo "  ✅ 健康检查返回 200"
echo "  ✅ 响应包含 status: ok"
echo "  ✅ PASSED"
echo ""
echo "---"
echo ""

# 示例 3: 前端响应式测试
echo -e "${BLUE}=== 示例 3: 前端响应式设计测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 验证页面在移动端的布局表现${NC}"
echo "命令:"
echo "  npx playwright test tests/frontend/responsive.spec.js -g '移动端布局'"
echo ""
echo "预期输出:"
echo "  ✅ 视口配置正确: width=device-width"
echo "  ✅ 内容适应移动端宽度（无横向滚动）"
echo "  ✅ body宽度: 375px ≤ 375px"
echo "  ✅ 移动端布局测试完成"
echo ""
echo "生成截图:"
echo "  reports/screenshots/responsive-mobile-375x667.png"
echo ""
echo "---"
echo ""

# 示例 4: 可访问性测试
echo -e "${BLUE}=== 示例 4: 可访问性测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 检查页面的 WCAG 2.0 可访问性标准${NC}"
echo "命令:"
echo "  npx playwright test tests/frontend/accessibility.spec.js -g '图片alt文本'"
echo ""
echo "预期输出:"
echo "  总图片数: 15"
echo "  有 alt 属性: 15"
echo "  空 alt 属性: 3 (装饰性图片)"
echo "  缺少 alt 属性: 0"
echo "  alt 覆盖率: 100.0%"
echo "  ✅ 图片 alt 覆盖率优秀 (>= 90%)"
echo ""
echo "---"
echo ""

# 示例 5: E2E 工作流测试
echo -e "${BLUE}=== 示例 5: E2E 建模工作流测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 完整的用户建模流程${NC}"
echo "命令:"
echo "  npx playwright test tests/e2e/modeling-workflow.spec.js --headed --slowmo 1000"
echo ""
echo "测试步骤:"
echo "  1. 访问首页 → 点击'开始建模'按钮"
echo "  2. 进入建模页面 → 拖拽'渠道'组件到画布"
echo "  3. 配置参数 → 长度:1000m, 底宽:5m, 坡度:0.001"
echo "  4. 点击'运行模拟'按钮 → 等待计算完成"
echo "  5. 查看结果 → 验证图表和数据表格"
echo "  6. 保存/导出 → 确认下载功能"
echo ""
echo "预期输出:"
echo "  ✅ 每个步骤都有截图保存到 reports/screenshots/"
echo "  ✅ 完整工作流测试通过"
echo ""
echo "---"
echo ""

# 示例 6: 性能测试
echo -e "${BLUE}=== 示例 6: API 性能压力测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 测试 API 在 50 用户并发下的性能${NC}"
echo "命令:"
echo "  locust -f tests/performance/test_api_load.py \\"
echo "         --host=http://localhost:8000 \\"
echo "         --headless \\"
echo "         --users 50 \\"
echo "         --spawn-rate 5 \\"
echo "         --run-time 60s \\"
echo "         --html reports/perf_demo.html"
echo ""
echo "预期输出:"
echo "  Name                      # reqs   # fails  Avg    Min    Max    Median   req/s"
echo "  GET /api/health           600      0        45ms   20ms   150ms  42ms     10.0"
echo "  GET /api/cases/list       300      0        120ms  50ms   300ms  115ms    5.0"
echo "  POST /api/solve/run       150      0        850ms  400ms  1500ms 820ms    2.5"
echo ""
echo "  ✅ P95 响应时间 < 200ms"
echo "  ✅ 错误率: 0%"
echo "  ✅ 吞吐量: 17.5 req/s"
echo ""
echo "生成报告:"
echo "  reports/perf_demo.html"
echo ""
echo "---"
echo ""

# 示例 7: 覆盖率报告
echo -e "${BLUE}=== 示例 7: 代码覆盖率报告 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 生成后端代码覆盖率报告${NC}"
echo "命令:"
echo "  pytest tests/backend/ \\"
echo "         --cov=solvers \\"
echo "         --cov=utils \\"
echo "         --cov-report=html:reports/coverage/demo \\"
echo "         --cov-report=term"
echo ""
echo "预期输出（终端）:"
echo "  Name                                    Stmts   Miss  Cover"
echo "  -----------------------------------------------------------"
echo "  solvers/godunov_fvm_solver.py            450     45    90%"
echo "  solvers/hydrostatic_canal_solver.py      380     20    95%"
echo "  solvers/hardycross_solver.py             280     30    89%"
echo "  utils/canal_utils.py                     120      8    93%"
echo "  utils/result_validator.py                 85      5    94%"
echo "  -----------------------------------------------------------"
echo "  TOTAL                                   1315    108    92%"
echo ""
echo "生成 HTML 报告:"
echo "  reports/coverage/demo/index.html"
echo ""
echo "---"
echo ""

# 示例 8: Docker 完整测试
echo -e "${BLUE}=== 示例 8: Docker 容器化测试 ===${NC}"
echo ""
echo -e "${YELLOW}场景: 在隔离的 Docker 环境中运行完整测试${NC}"
echo "命令:"
echo "  docker-compose -f docker-compose.test.yml up test-runner"
echo ""
echo "Docker 输出:"
echo "  Creating network 'hydroclaude_test-network' ... done"
echo "  Creating hydroclaude-backend-test ... done"
echo "  Creating hydroclaude-test-runner ... done"
echo "  等待后端服务..."
echo "  运行后端测试..."
echo "  ============================= test session starts =============================="
echo "  tests/backend/solvers/test_godunov_commercial.py::test_dam_break PASSED [ 10%]"
echo "  tests/backend/solvers/test_hydrostatic_commercial.py::test_uniform_flow PASSED [ 20%]"
echo "  ..."
echo "  ============================== 42 passed in 12.34s =============================="
echo "  运行 API 测试..."
echo "  ============================== 15 passed in 5.67s ==============================="
echo "  测试完成！"
echo ""
echo "报告位置:"
echo "  reports/html/backend_test_report.html"
echo "  reports/coverage/backend/index.html"
echo ""
echo "---"
echo ""

# 实际执行建议
echo -e "${GREEN}=========================================="
echo "实际执行建议"
echo "==========================================${NC}"
echo ""
echo "1. 快速验证（5分钟）"
echo "   bash scripts/demo_tests.sh"
echo "   选择选项 1: 环境检查"
echo ""
echo "2. 后端测试（10分钟）"
echo "   pytest tests/backend/solvers/test_hydrostatic_commercial.py -v"
echo ""
echo "3. 前端测试（15分钟）"
echo "   npm run test:chromium -- --grep='响应式'"
echo ""
echo "4. 完整测试（30分钟）"
echo "   bash scripts/demo_tests.sh"
echo "   选择选项 8: 完整测试流程"
echo ""
echo "5. 查看报告"
echo "   open reports/html/test_report.html"
echo "   open reports/coverage/index.html"
echo ""

echo -e "${YELLOW}=========================================="
echo "查看更多示例"
echo "==========================================${NC}"
echo ""
echo "详细指南: QUICK_START_TESTING.md"
echo "交互演示: bash scripts/demo_tests.sh"
echo "环境检查: python3 tests/test_environment.py"
echo ""
