#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HydroClaude 示例代码生成器

自动生成符合开发规范的示例代码框架，确保从一开始就使用基础库。

特点:
-  自动包含所有必要的基础库导入
-  遵循标准代码结构
-  提供清晰的TODO标记
-  自动创建输出目录
-  支持多种模板类型

用法:
    python tools/create_example.py <名称> <描述> [选项]
    
示例:
    # 创建基本示例
    python tools/create_example.py my_canal_test "单闸门流动分析"
    
    # 创建带控制的示例
    python tools/create_example.py my_mpc_test "MPC控制案例" --template control
    
    # 指定作者
    python tools/create_example.py my_test "测试案例" --author "Alice"

Author: HydroClaude Development Team
Date: 2025-10-27
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime

# ========== 代码模板 ==========

BASIC_TEMPLATE = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
{description}

功能说明:
- 使用 HydrostaticCanalSolver 进行稳态求解
- 使用 ResultValidator 自动验证结果
- 使用 PlotHelper 生成专业图表

Author: {author}
Date: {date}
Generated by: HydroClaude Example Generator
"""

import sys, os

# ========== 路径设置 ==========
script_path = os.path.abspath(__file__)
project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_path)))
sys.path.insert(0, project_root)

# ========== 基础库导入（必须使用）==========
from solvers.hydrostatic_canal_solver import HydrostaticCanalSolver
from solvers.gate import SluiceGate, BroadCrestedWeir, Orifice
from utils.canal_utils import compute_steady_uniform_flow, compute_critical_depth
from utils.result_validator import quick_validate_steady_state
from utils.plot_helper import PlotHelper

import numpy as np
import matplotlib.pyplot as plt


def main():
    """主函数"""
    print("=" * 80)
    print("{description}")
    print("=" * 80)
    
    # ========== 1. 参数设置 ==========
    print("\\n1. 参数设置")
    print("-" * 80)
    
    # 渠道参数
    length = 10000.0  # 渠道长度 (m)
    nx = 301  # 网格数（推荐奇数）
    B = 10.0  # 渠道宽度 (m)
    S0 = 0.001  # 渠底坡度
    n = 0.025  # Manning糙率系数
    
    # 流量参数
    Q_target = 10.0  # 目标流量 (m³/s)
    
    print(f"  渠道长度: {{length}} m")
    print(f"  渠道宽度: {{B}} m")
    print(f"  底坡: {{S0}}")
    print(f"  目标流量: {{Q_target}} m³/s")
    
    # TODO: 根据需要修改参数
    
    # ========== 2. 创建结构物（可选）==========
    print("\\n2. 创建结构物")
    print("-" * 80)
    
    # TODO: 如果需要结构物，取消注释以下代码
    # gate = SluiceGate(
    #     position=5000.0,  # 位置 (m)
    #     width=B,          # 宽度 (m)
    #     opening=5.0,      # 开度 (m)
    #     Cd=0.6            # 流量系数
    # )
    # print(f"  创建闸门: 位置={5000.0}m, 开度={5.0}m")
    
    internal_structures = []  # TODO: 添加结构物到列表
    # internal_structures = [(5000.0, gate)]
    
    # ========== 3. 创建求解器 ==========
    print("\\n3. 创建求解器")
    print("-" * 80)
    
    solver = HydrostaticCanalSolver(
        length=length,
        nx=nx,
        B=B,
        S0=S0,
        n=n,
        internal_structures=internal_structures
    )
    print(f"  求解器创建成功")
    print(f"  网格数: {{nx}}")
    print(f"  空间步长: {{solver.dx:.2f}} m")
    
    # ========== 4. 初始化（使用基础库）==========
    print("\\n4. 初始化")
    print("-" * 80)
    
    # 计算均匀流水深（使用基础库）
    h_uniform = compute_steady_uniform_flow(Q_target, B, S0, n)
    print(f"  均匀流水深: {{h_uniform:.4f}} m")
    
    # 初始化求解器
    solver.h[:] = h_uniform
    solver.hu[:] = Q_target / B
    print(f"  初始化完成")
    
    # ========== 5. 稳态求解 ==========
    print("\\n5. 稳态求解")
    print("-" * 80)
    
    result = solver.solve_steady_state(
        Q_target=Q_target,
        h_downstream=h_uniform,
        max_iterations=5000,
        convergence_tol=0.1,  # 推荐：宽松容差，极快收敛
        dt=0.5,
        verbose=True
    )
    
    # ========== 6. 验证结果（必须使用基础库！）==========
    print("\\n6. 结果验证")
    print("-" * 80)
    
    validator = quick_validate_steady_state(
        solver=solver,
        result_dict=result,
        Q_target=Q_target,
        name="{description}"
    )
    
    # ========== 7. 可视化（使用基础库）==========
    print("\\n7. 生成可视化")
    print("-" * 80)
    
    plotter = PlotHelper()
    
    # 7.1 纵剖面图
    fig = plotter.plot_profile(
        solver.x / 1000,  # 转换为km
        result['h'],
        xlabel="Distance (km)",
        ylabel="Water Depth (m)",
        title="{description} - 水深剖面",
        # TODO: 如果有结构物，取消注释以下行
        # structures=[(5.0, "Gate")],  # 位置以km为单位
        save_path="results/profile.png"
    )
    plt.close(fig)
    print("   保存纵剖面图: results/profile.png")
    
    # 7.2 流量分布图（可选）
    # TODO: 如果需要流量验证图，取消注释
    # fig = plotter.plot_profile(
    #     solver.x / 1000,
    #     result['Q'],
    #     xlabel="Distance (km)",
    #     ylabel="Flow Rate (m³/s)",
    #     title="Flow Distribution",
    #     save_path="results/flow.png"
    # )
    # plt.close(fig)
    # print("   保存流量分布图: results/flow.png")
    
    # ========== 8. 保存数据（可选）==========
    print("\\n8. 保存数据")
    print("-" * 80)
    
    # TODO: 如果需要保存数据，取消注释
    # import pandas as pd
    # df = pd.DataFrame({{
    #     'x': solver.x,
    #     'h': result['h'],
    #     'Q': result['Q']
    # }})
    # df.to_csv('results/data.csv', index=False)
    # print("   保存数据: results/data.csv")
    
    # ========== 9. 总结 ==========
    print("\\n" + "=" * 80)
    print("完成！")
    print("=" * 80)
    print(f"\\n关键结果:")
    print(f"  收敛状态: {{'' if result['converged'] else ''}}")
    print(f"  迭代次数: {{result['iterations']}}")
    print(f"  流量误差: {{result['Q_error_percent']:.6f}}%")
    print(f"  最小水深: {{result['h_min']:.4f}} m")
    print(f"  最大水深: {{result['h_max']:.4f}} m")
    
    return validator


if __name__ == '__main__':
    validator = main()
'''

CONTROL_TEMPLATE = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
{description}

功能说明:
- 使用 Canal (Preissmann) 进行非恒定流模拟
- 实现PID/MPC控制
- 使用 PlotHelper 生成时间序列图

Author: {author}
Date: {date}
Generated by: HydroClaude Example Generator
"""

import sys, os

# ========== 路径设置 ==========
script_path = os.path.abspath(__file__)
project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_path)))
sys.path.insert(0, project_root)

# ========== 基础库导入 ==========
from physics.canal import Canal
from control.pid_controller import PIDController
from utils.plot_helper import PlotHelper

import numpy as np
import matplotlib.pyplot as plt


def main():
    """主函数"""
    print("=" * 80)
    print("{description}")
    print("=" * 80)
    
    # ========== 1. 参数设置 ==========
    print("\\n1. 参数设置")
    print("-" * 80)
    
    # 渠道参数
    length = 5000.0  # 渠道长度 (m)
    width = 10.0  # 渠道宽度 (m)
    slope = 0.001  # 渠底坡度
    manning_n = 0.025  # Manning糙率
    
    # 仿真参数
    dt = 10.0  # 时间步长 (s)
    T_total = 3600.0  # 总仿真时间 (s)
    n_steps = int(T_total / dt)
    
    # 控制参数
    target_depth = 2.5  # 目标水深 (m)
    
    print(f"  仿真时长: {{T_total}} s")
    print(f"  时间步长: {{dt}} s")
    print(f"  目标水深: {{target_depth}} m")
    
    # TODO: 修改参数
    
    # ========== 2. 创建渠道 ==========
    print("\\n2. 创建渠道")
    print("-" * 80)
    
    canal = Canal(
        name="Canal",
        volume_min=0,
        volume_max=length * width * 10,  # 最大容积
        area=length * width,
        length=length,
        width=width,
        slope=slope,
        manning_n=manning_n,
        method='preissmann',  # 唯一可用
        n_sections=51,
        initial_depth=2.0,
        initial_flow=20.0
    )
    print(f"  渠道创建成功")
    
    # ========== 3. 创建控制器 ==========
    print("\\n3. 创建控制器")
    print("-" * 80)
    
    # TODO: 根据需要选择PID或MPC控制器
    controller = PIDController(
        kp=1.0,  # 比例增益
        ki=0.1,  # 积分增益
        kd=0.0   # 微分增益
    )
    print(f"  PID控制器创建成功")
    
    # ========== 4. 时间循环 ==========
    print("\\n4. 开始仿真")
    print("-" * 80)
    
    # 记录历史
    time_history = []
    depth_history = []
    flow_history = []
    
    Q_upstream = 20.0  # 上游流量
    
    for step in range(n_steps):
        t = (step + 1) * dt
        
        # 获取当前状态
        current_depth = canal.state.level
        
        # TODO: 实现控制逻辑
        # 示例：计算控制量
        # error = target_depth - current_depth
        # Q_downstream = controller.compute(error)
        
        Q_downstream = 20.0  # TODO: 替换为控制器输出
        
        # 更新渠道
        canal.update_high_fidelity(dt, {{
            'upstream_flow': Q_upstream,
            'downstream_flow': Q_downstream
        }})
        
        # 记录数据
        time_history.append(t)
        depth_history.append(current_depth)
        flow_history.append(canal.state.flow)
        
        # 打印进度
        if step % 100 == 0:
            print(f"  t={{t:.0f}}s, h={{current_depth:.3f}}m")
    
    print("  仿真完成")
    
    # ========== 5. 可视化 ==========
    print("\\n5. 生成可视化")
    print("-" * 80)
    
    plotter = PlotHelper()
    
    # 时间序列图
    fig = plotter.plot_time_series(
        np.array(time_history),
        np.array(depth_history),
        xlabel="Time (s)",
        ylabel="Water Depth (m)",
        title="{description} - 水深演化",
        reference_lines=[(target_depth, "Target")],
        save_path="results/depth_evolution.png"
    )
    plt.close(fig)
    print("   保存时间序列图: results/depth_evolution.png")
    
    # ========== 6. 总结 ==========
    print("\\n" + "=" * 80)
    print("完成！")
    print("=" * 80)
    print(f"\\n关键结果:")
    print(f"  最终水深: {{depth_history[-1]:.4f}} m")
    print(f"  平均水深: {{np.mean(depth_history):.4f}} m")
    print(f"  水深标准差: {{np.std(depth_history):.4f}} m")


if __name__ == '__main__':
    main()
'''

# ========== 生成器函数 ==========

def create_example(name: str, description: str, author: str = "HydroClaude", 
                   template: str = "basic") -> Path:
    """
    生成示例代码
    
    Args:
        name: 示例名称（用作目录名和文件名）
        description: 示例描述
        author: 作者名称
        template: 模板类型（"basic" 或 "control"）
    
    Returns:
        生成的脚本文件路径
    """
    # 选择模板
    if template == "control":
        code_template = CONTROL_TEMPLATE
    else:
        code_template = BASIC_TEMPLATE
    
    # 创建输出目录
    output_dir = Path('examples') / name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 创建脚本文件
    script_path = output_dir / f"{name}.py"
    
    # 填充模板
    code = code_template.format(
        description=description,
        author=author,
        date=datetime.now().strftime('%Y-%m-%d')
    )
    
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(code)
    
    # 创建results目录
    (output_dir / 'results').mkdir(exist_ok=True)
    
    # 创建README
    readme_content = f"""# {description}

**生成日期**: {datetime.now().strftime('%Y-%m-%d')}
**作者**: {author}
**模板类型**: {template}

## 运行方法

```bash
python {script_path}
```

## 输出文件

- `results/profile.png` - 纵剖面图
- `results/flow.png` - 流量分布图（如果启用）
- `results/data.csv` - 数据文件（如果启用）

## 修改提示

文件中包含多个 `TODO` 注释，标记了需要自定义的地方：

1. 修改参数（长度、宽度、流量等）
2. 添加结构物（闸门、堰等）
3. 启用可选功能（保存数据、额外图表等）

## 注意事项

-  已使用 HydrostaticCanalSolver（推荐求解器）
-  已使用 ResultValidator 验证结果
-  已使用 PlotHelper 生成图表
-  已使用 canal_utils 计算水力学参数

不要修改基础库的导入和使用方式！
"""
    
    readme_path = output_dir / 'README.md'
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    return script_path, readme_path


def main():
    """主函数"""
    parser = argparse.ArgumentParser(
        description='HydroClaude 示例代码生成器',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 创建基本示例
  python tools/create_example.py my_canal_test "单闸门流动分析"
  
  # 创建控制示例
  python tools/create_example.py my_mpc_test "MPC控制案例" --template control
  
  # 指定作者
  python tools/create_example.py my_test "测试案例" --author "Alice"
        """
    )
    
    parser.add_argument('name', help='示例名称（用作目录名）')
    parser.add_argument('description', help='示例描述')
    parser.add_argument('--author', default='HydroClaude', help='作者名称（默认：HydroClaude）')
    parser.add_argument('--template', choices=['basic', 'control'], default='basic',
                        help='模板类型（默认：basic）')
    
    args = parser.parse_args()
    
    # 生成示例
    print("=" * 80)
    print("HydroClaude 示例代码生成器")
    print("=" * 80)
    print(f"\n生成示例: {args.name}")
    print(f"描述: {args.description}")
    print(f"作者: {args.author}")
    print(f"模板: {args.template}")
    print()
    
    script_path, readme_path = create_example(
        args.name,
        args.description,
        args.author,
        args.template
    )
    
    print(" 示例生成成功！")
    print(f"\n生成的文件:")
    print(f"   脚本: {script_path}")
    print(f"   文档: {readme_path}")
    print(f"   输出: {script_path.parent / 'results'}")
    
    print(f"\n下一步:")
    print(f"  1. 编辑脚本: {script_path}")
    print(f"  2. 搜索 'TODO' 注释，修改参数和配置")
    print(f"  3. 运行: python {script_path}")
    print(f"  4. 查看结果: {script_path.parent / 'results'}")
    
    print("\n" + "=" * 80)


if __name__ == '__main__':
    main()
